name: Firestore Indexes Deployment

on:
  push:
    branches: [master]
    paths:
      - '.github/workflows/deploy-indexes.yml'
      - 'firestore.indexes.json'
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 12
      - uses: w9jds/firebase-action@master
        with:
          args: deploy --only firestore:indexes
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}